[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
positioned-io = "0.3.3"
num_cpus = "1.14.0"
dashmap = "5.5.3"
serde_json = "1.0"

[profile.release]
lto = true